spring.application.name=Vehicles
server.port=8080
spring.datasource.url=jdbc:postgresql://ep-tiny-sun-adjcls8j-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_UNLQK0lWpd2a&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UNLQK0lWpd2a
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret = c8770cf4f12e530bf6a73dfa4ef245a73acfb7eb5ad0dc27550937d8549183e7e3534007
jwt.expiration = 3600000